
// The requirements for IEV terminological entries are specified in the IEC Supplement to the ISO/IEC Directives, Annex SK.
// Further information can be found at www.iec.ch/standardsdev/resources/draftingpublications/writing_editing/directives/terms_definitions.htm


[[terms]]
== Terms and definitions

=== General

[[en-term-script]]
==== English preferred term

alt:[English admitted term]

deprecated:[English deprecated term]

domain:[specific use]

definition written as a descriptive statement that can replace the term in context

// non-verbal representation of the concept (e.g. mathematical formula or illustration)

stem:[bar U(t_1, t_2)]

====
Information that illustrates the concept.
====

NOTE: Additional information, e.g. units, provisions relating to the use of the term.

[.source]
<<ISO5127,clause="3.1.6.02">>, Description of modification


////
not modelled yet:

* symbols for the concept
* attributes (for each of preferred, admitted, deprecated terms)
* putting in domain as speciifc usage under <usage>, assuming it to repeat for each term
* French equivalent
* equivalent term in additional IEV language

////
